name: iksemel

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --yes -qq build-essential autoconf libtool git python3 python3-dev ninja-build meson
    - name: Basic meson build generation
      run: |
        meson build -Dwith_tests=true
    - name: Ninja source build
      run: |
        cd build 
        ninja
    - name: Ninja tests
      run: |
        cd build
        ninja tests
    - name: Prepare artifacts
      if: failure()
      run: |
        - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: Logs
        path: |
          /home/runner/work/iksemel/iksemel/build/meson-logs/meson-log.txt 
        if-no-files-found: ignore

