name: iksemel with gnutls

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --yes -qq build-essential autoconf libtool git python3 python3-dev python3-setuptools gnutls-dev gnutls-bin
    - name: Install meson via pip
      run: |
        sudo pip3 install meson
        sudo pip3 install Ninja

    - name: Basic meson build generation with gnutls support
      run: |
        meson build  -D openssl=disabled -D gnutls=enabled
    - name: Ninja source build
      run: |
        ninja -C build
    - name: Ninja tests
      run: |
        ninja -C build test
    - name: Prepare artifacts
      if: failure()
      run: |
          cat /home/runner/work/iksemel/iksemel/build/meson-logs/meson-log.txt
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: Logs
        path: |
          /home/runner/work/iksemel/iksemel/build/meson-logs/meson-log.txt
        if-no-files-found: ignore

