name: iksemel

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --yes -qq build-essential autoconf libtool git python3 python3-dev python3-setuptools gnutls-dev gnutls-bin valgrind
    - name: Install meson via pip
      run: |
        sudo pip3 install meson
        sudo pip3 install Ninja
    - name: Basic meson build generation
      run: |
        meson build
    - name: Ninja source build
      run: |
        ninja -C build
    - name: Ninja tests
      run: |
        ninja test -C build
    - name: Valgrind tests
      run: |
        cd build 
        meson test --wrap='valgrind --leak-check=full --error-exitcode=1' --no-rebuild 
    - name: Prepare artifacts
      if: failure()
      run: |
          cat /home/runner/work/iksemel/iksemel/build/meson-logs/meson-log.txt
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: Logs
        path: |
          /home/runner/work/iksemel/iksemel/build/meson-logs/meson-log.txt
          /home/runner/work/iksemel/iksemel/build/meson-logs/testlog-valgrind.txt
        if-no-files-found: ignore

